---
master_list:
- 169.45.103.134
public_agent_list:
- 169.45.103.144
agent_list:
- 169.45.103.145
- 169.45.103.130
bootstrap_url: file:///opt/dcos_install_tmp
cluster_name: STC-MESOS
exhibitor_storage_backend: static
ip_detect_filename: /genconf/ip-detect-sl
master_discovery: static
oauth_enabled: true
process_timeout: 10000
resolvers:
- 8.8.8.8
- 8.8.4.4
ssh_port: 22
ssh_user: root
telemetry_enabled: false
