---
agent_list:
- 172.16.157.167
- 172.16.157.170
- 172.16.157.171
- 172.16.157.198
- 172.16.157.199
bootstrap_url: file:///opt/dcos_install_tmp
cluster_name: STC-MESOS
exhibitor_storage_backend: static
ip_detect_filename: /genconf/ip-detect
master_discovery: static
master_list:
- 172.16.155.140
oauth_enabled: false
process_timeout: 10000
resolvers:
- 8.8.8.8
- 8.8.4.4
ssh_port: 22
ssh_user: root
telemetry_enabled: false
