---
master_list:
- 9.30.230.8
public_agent_list:
- 9.30.147.71
agent_list:
- 9.30.54.100
- 9.30.245.28
- 9.30.245.33
- 9.30.245.43
- 9.30.245.44
- 9.30.245.45
bootstrap_url: file:///opt/dcos_install_tmp
cluster_name: STC-MESOS
exhibitor_storage_backend: static
ip_detect_filename: /genconf/ip-detect-svl
master_discovery: static
oauth_enabled: true
process_timeout: 10000
resolvers:
- 8.8.8.8
- 8.8.4.4
ssh_port: 22
ssh_user: root
telemetry_enabled: false
